### PR TITLE
Update TriggerHandler.cls with a feature for disabling Triggers via a custom setting field

### PR DESCRIPTION
**Pull request by dancinllama**
Added a protected method and logic to the validateRun() method for the ability to disable a trigger from a hierarchy custom setting (in this case called Trigger_Enablement__c).

### CODE REVIEW

**Comment by kevinohara80** [comment]
@codefriar circling back to this really old PR from our buddy, @dancinllama. I've gone back and forth on this. Should a custom setting be included in the TriggerHandler that allows for disabling triggers? I was for it at one point but I'm leaning towards letting userland implement this if they want it.

**Comment by codefriar** [comment]
I’m for it, with caveats.

I’d like to see it be a custom metadata type rather than a custom setting — means it’s  deployable. and I think there should be a decent ui for it. Maybe we can get James to do that?

-Kevin

-- 
Kevin Poorman
My Strengths Finder 2.0 top 5 are: Ideation, Connectedness, Strategic, Input and Futuristic.

On June 3, 2015 at 9:41:00 PM, kevinohara80 (notifications@github.com) wrote:

@codefriar circling back to this really old PR from our buddy, @dancinllama. I've gone back and forth on this. Should a custom setting be included in the TriggerHandler that allows for disabling triggers? I was for it at one point but I'm leaning towards letting userland implement this if they want it.

**Comment by Xtremefaith** [comment]
Is this different than the already available trigger bypass which works pretty well?

**Comment by kevinohara80** [comment]
This is really old so I'm going to close it. I'm still in favor of a custom metadata type for configuration but I don't feel it's necessary. If a PR comes through I'll review it.

**Pull request closed without merging**
