### PR TITLE
Added methods to bypass/clear bypass for many handlers at once.

### PR DESCRIPTION
**Pull request by renatoliveira**
I've found this to be useful on certain tests when I need to bypass an object handler and its children (like Account and Opportunity) on the same test. Less lines of code.

### CODE REVIEW

**Comment by kaszy86** [comment]
Hi @renatoliveira! Small suggestion for your methods to support bypassing/clearing multiple handlers at once - you could use removeAll() in bypass/clearBypass and directly pass a list or set with the elements you want removed from bypassedHandlers instead of looping through.

**Comment by kevinohara80** [comment]
@renatoliveira This PR is hard to review because it's reformatted to a 4-space indentation versus the 2-space that's used in this library. Can you reformat this back to 2-space so I can see a clean diff?

**Comment by vr8hub** [comment]
Hey, @renatoliveira, would you be willing to reformat this so @kevinohara80 can review it? I like the changes and would like to see them incorporated. If not, would you mind me submitting a reformatted one? Thanks!

**Comment by renatoliveira** [comment]
> Hey, @renatoliveira, would you be willing to reformat this so @kevinohara80 can review it? I like the changes and would like to see them incorporated. If not, would you mind me submitting a reformatted one? Thanks!

Feel free to submit a reformatted one!

**Comment by vr8hub** [comment]
Will do, thanks for the reply.

**Pull request closed without merging**
